### ISSUE TITLE
"--Normalize" always returns the normalized vector for vector1

### ISSUE THREAD

**Issue by AtleSkaanes** [KneeCapStealer/ChristofferFirstPythonRepo#1]
When you type the command ´--Normalize´, you are given the choice between what vector you want to normalize (either 1 or 2).
But no matter what input you give, it returns the normalized vector of vector1.

Example:
```
Vælg en vektor der skal normaliseres
Skriv enten 1 eller 2
2
Vektor1 = [x: 32767.0, y: 2147483647.0]
Vektor1.normalize() = [x: 1.5258323406541709e-05, y: 0.9999999998835918]
```

**Comment by KneeCapStealer** [comment]
Aight bro will see what i can do

**Comment by KneeCapStealer** [comment]
Problem should be fixed now :)

**Comment by Robotto** [comment]
Try using links to specific commits and lines in files. it's awesome:

https://github.com/KneeCapStealer/ChristofferFirstPythonRepo/blob/03d6f3d76644ccb19bfa15d8b43fe890516f9de6/main.py#L9

03d6f3d
