### ISSUE TITLE
Your program SUCKS... just kidding its awesome!

### ISSUE THREAD

**Issue by J0pper** [KneeCapStealer/ChristofferFirstPythonRepo#2]
### --Length af en vektor virker ikke
Det ser ud til at du bare glemte at tilføje to bindestreger foran "Lenght" i case-navnet :)

### Fejl når man skriver andet en et tal 😛
Når jeg er dum og træls og en dårlig bruger og prøver at skrive andet end et tal ved definitionen af en vektor fejler programmet. Du ved sikkert godt, hvordan man fikser det (i don't xD).

**Comment by KneeCapStealer** [comment]
Har fixed commanden og har fixet fejlen med invalid argumenter :)
